name: Create and Release PHAR

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Configure PHP for PHAR
        run: |
          echo "phar.readonly=0" | sudo tee -a /etc/php/8.3/cli/conf.d/99-disable-phar.ini

      - name: Install Dependencies
        run: composer install --no-dev --no-progress

      - name: Execute the PHAR Maker Script
        run: php scripts/makephar.php

      - name: Release
        run: |
          TAG=${{ github.ref_name }}
          echo "Creating release for $TAG"
          gh release create "$TAG" scripts/easy-ini.phar --title "$TAG"

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
